# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags: '*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get the version number
        run: "::set-output name=VERNUM::$(awk -F'\"' '/version_number/ { print $4 }' manifest.json)"
        id: version-number

      - name: Compress the files into a zip archive
        uses: thedoctor0/zip-release@master
        with:
          filename: "BroheimModpack-${{steps.version-number.outputs.VERNUM}}.zip"
          exclusions: "*.git*"
        
      - name: Upload artifacts as release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "BroheimModpack-${{steps.version-number.outputs.VERNUM}}.zip"
          token: ${{secrets.GITHUB_TOKEN}}
          tag: v${{steps.version-number.outputs.VERNUM}}
